spring:
  application.name: post-application

  datasource:
    url: jdbc:postgresql://localhost:5432/board?characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: dev-user
    password: secret!@#

  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
